### ISSUE TITLE
v1.3.4 has new strings need translate

### ISSUE THREAD

**Issue by imgdrive** [dvdforge/imgdrive_translations#12]
@eson57 @MatejGolian @c-sanchez @gokronikos 
http://download.yubsoft.com/ImgDrive_1.3.5.exe
Change log:
- Added Hide unmounted drives
- Added Create ISO image which can create DVD/Blu-ray compatible disc images
- Added Show ImgDrive in system tray
- Added change drive letter
- Updated kernel drive version to 1.2
- Fixed portable edition install failure on Windows 2000
- Some minor changes

The new english strings already merged to all .ini files, appropriated you could review the latest language file in GitHub.

v1.3.4 also add trivial license code which proves that ImgDrive is your unique version, please send mail with the **Name** you want to shown in ImgDrive to support@yubsoft.com if you need the license code.
![imgdrive134](https://user-images.githubusercontent.com/19568093/36341417-e762466c-1428-11e8-8c2d-c53d562eb6af.png)

**Comment by imgdrive** [comment]
BTW:
 ImgDrive_XXX.ini line 17:
11=[Please customize translator information]
will be shown in options dialog, you can changed it like:
11=translated by Yang

**Comment by c-sanchez** [comment]
There are 3 missing translation strings in 1.3.4 beta, making an iso image we have:
"Writing", "Finished" and "Operation successfully completed!"

If possible add this please.

Regards.

**Comment by imgdrive** [comment]
@c-sanchez 
Added to my to-do list, there are many hard-code strings in image author module, i will sort them when this module's more stable.

Thank you for report this issue.
