### ISSUE TITLE
Main Window: Gray Out the Mount Image Item if No Drive Is Selected In The List

### ISSUE THREAD

**Issue by MatejGolian** [dvdforge/imgdrive_translations#14]
Perhaps it would be a good idea to gray out (disable) the mount image item in the file menu of the main window if there are no drives enabled or if no drive is selected in the list of drives.

**Comment by imgdrive** [comment]
http://download.yubsoft.com/ImgDrive_1.3.4_beta2.exe

is fixed, thank u.

**Comment by MatejGolian** [comment]
Great, thanks a lot! :-)
