### ISSUE TITLE
Change Drive Letter & System Drive Properties Options Missing When No Image Mounted

### ISSUE THREAD

**Issue by MatejGolian** [dvdforge/imgdrive_translations#15]
I don't know if it's possible as there could be some Windows limitations connected to this, but could you add the items "Change Drive Letter" and "System Drive Preferences" to the context menus of drives that currently do not have images mounted to them as well? At present these only appear with mounted drives. If it's possible, could you add them both to the tray and main window context menus?
Many thanks.

**Comment by imgdrive** [comment]
http://download.yubsoft.com/ImgDrive_1.3.4_beta2.exe

is fixed, thank u.

**Comment by MatejGolian** [comment]
Thanks, works perfect. :-)
