### ISSUE TITLE
Adjust Behavior for Reopening from Tray Icon

### ISSUE THREAD

**Issue by MatejGolian** [dvdforge/imgdrive_translations#16]
If you have the  system tray option enabled, I think that double-clicking the ImgDrive tray icon should always open the main window. Currently double-clicking the ImgDrive icon only shows the main window if the main window is already opened.

**Comment by imgdrive** [comment]
http://download.yubsoft.com/ImgDrive_1.3.4_beta2.exe

is fixed, thank u.

**Comment by MatejGolian** [comment]
No, thank you. :-)
