### ISSUE TITLE
Multilingual installer

### ISSUE THREAD

**Issue by bovirus** [dvdforge/imgdrive_translations#18]
@dvdforge 

I'm the official Italian translator of InnoSetup and NSIS (programs to create the installer).

I posted a pullup request about an update of ImgDrive Italian language.

I'd like to help you to make your installer multilanguage.

If you post into the GitHub the 

.iss (InnoSetup Installer Script)
license file (to translate it into several languages)

 we can help you to make the installer multi-language

Thanks.

**Comment by imgdrive** [comment]
Thank u, current has no plan to make the installer/license file multi-language, it's just a freeware, and the installation progress is straightforward, i'll keep it small and simple, hope you understand.

**Comment by bovirus** [comment]
@dvdforge 

Sorry but I'm not agree about it.

Also if it's a freeware it's more professional to have multilanguage installer.
**_And it's require 5 minutes._**

If you want I can transform the single language installer in multi-language installer in 5 minutes (maximum time requested to do it).

Please provide here (or via email - you have it) and I will reply in 5 minute with new installer file.

If you post the installer script any person can help you with the specific icon description texts.

I already made the license for Italian. Not required additional time for you.

**_Please remind to merge the Italian language pull up request._**

Thanks. best regards.
