### ISSUE TITLE
Update ImgDrive_SPA.ini

### ISSUE THREAD

**Issue by c-sanchez** [dvdforge/imgdrive_translations#20]
https://github.com/c-sanchez/imgdrive_translations/commit/7f6323cb8b8f35e24c4d79fedbd1bee061b229b2

I've used the "Commit directly to the master branch." but I do not know what exactly happens.

**Comment by imgdrive** [comment]
merged, thank you.

You are collaborator now, i think you could edit the file directly online:
https://github.com/dvdforge/imgdrive_translations/edit/master/ImgDrive_SPA.ini

**Comment by bovirus** [comment]
@c-sanchez
 
Please also translate if you can and post here the translation for icon descriptions

Website of ImgDrive
Uninstall ImgDrive

**Comment by imgdrive** [comment]
> I have change the innosetup script with:
> {group}\{cm:ProgramOnTheWeb,ImgDrive}
> {group}\{cm:UninstallProgram,ImgDrive}
> 
> [Languages]
> ; https://baike.so.com/doc/6727542-6941815.html
> Name: "en"; MessagesFile: "compiler:Default.isl"
> Name: "jp"; MessagesFile: "compiler:Languages\Japanese.isl"
> Name: "fr"; MessagesFile: "compiler:Languages\French.isl"
> Name: "de"; MessagesFile: "compiler:Languages\German.isl"
> Name: "it"; MessagesFile: "compiler:Languages\Italian.isl"
> ;Name: "pl"; MessagesFile: "compiler:Languages\Polish.isl"
> Name: "ru"; MessagesFile: "compiler:Languages\Russian.isl"
> Name: "pt"; MessagesFile: "compiler:Languages\Portuguese.isl"
> Name: "es"; MessagesFile: "compiler:Languages\Spanish.isl"
> Name: "cn"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

By default will use the current OS language's custom strings in innosetup .lng files.

**Comment by bovirus** [comment]
@dvdforge 
Thanks. Right.
For me it's better use as much is possible the strings in Inno Setup ISL language files.

**Comment by c-sanchez** [comment]
@bovirus ok, this are the translations:
Sitio web de ImgDrive
Desinstalar ImgDrive

I'm sorry for my delay

@dvdforge thank you very much, yep, I can modify the file directly now :)
