### ISSUE TITLE
ImgDrive v1.4.5 new strings need to be translated

### ISSUE THREAD

**Issue by imgdrive** [dvdforge/imgdrive_translations#21]
@bovirus @MatejGolian @c-sanchez @Pentive 
[ImgDrive_1.4.5 beta](http://download.yubsoft.com/ImgDrive_1.4.5.exe)

[DIALOG_11]
0=General
3=Vendor:
4=Model:
5=Firmware Version:
6=Firmware Date:
7=Serial Number:
8=Buffer Size:
9=Region Code:
10=Region Control:
11=User Changes Left:
12=Vendor Changes Left:

[DIALOG_12]
0=Features
3=Read Features
4=Write Features
5=Other Features

[DIALOG_13]
0=Media

[DIALOG_14]
0=File Explorer

[DIALOG_15]
0=Sector Viewer
3=LBA:

[STRING]
28=System Device &Properties => 28=Device &Properties

60=Erasing disc
61=Formatting disc
62=Writing
63=Synchronizing cache
64=Finished
65=Refresh
66=LBA
67=Size
68=Size (Bytes)
69=Date Modified
70=File Explorer
71=Sector Viewer
72=E&xtract File
73=Session %d
74=Track %d
75=Session
76=Track

**Comment by bovirus** [comment]
@dvdforge 

[DIALOG_11]
0=Generale
3=Produttore:
4=Modello:
5=Versione firmware:
6=Data firmware:
7=Numero seriale:
8=Dimensione buffer:
9=Codice regionale:
10=Controllo regionale:
11=Modifiche utente rimanenti:
12=Modifiche produttore rimanenti:

[DIALOG_12]
0=Funzionalità
3=Funzionalità lettura
4=Funzionalità scrittura
5=Altre funzionalità

[DIALOG_13]
0=Media

[DIALOG_14]
0=Esplora file

[DIALOG_15]
0=Visualizzatore settore
3=LBA:

[STRING]
28=&Proprietà dispositivo

60=Cancellazione disco
61=Formattazione disco
62=Scrittura
63=Sincronizzazione cache
64=Completata
65=Aggiorna
66=LBA
67=Dimensione
68=Dimensione (Byte)
69=Data modifica
70=Esplora file
71=Visualizzatore settore
72=E&strai file
73=Sessione %d
74=Traccia %d
75=Sessione
76=Traccia

I already commit the changes to the Italian langaueg file (as v. 1.4.5).
I edited the English language changing version number from 1.4.0 to 1.4.5
