### ISSUE TITLE
Installer - Add option to set "Start with Windows"

### ISSUE THREAD

**Issue by bovirus** [dvdforge/imgdrive_translations#24]
Hi.

I propose you to modify the installer, if you can, to add an option to set during installation the option "Start with Windows" (ON/OFF).

Thanks.

**Comment by imgdrive** [comment]
i know little about innosetup script, do you have sample code?

**Comment by bovirus** [comment]
I will make a search about the function for Inno Setup.

**Comment by MatejGolian** [comment]
Here are a few topics on the subject. From what I understand, the 'registry method' is the more appropriate one for ImgDrive. The examples posted there do not cover creating the checkbox in the installer, but that shouldn't be hard to do:
https://stackoverflow.com/questions/13244181/inno-setup-app-start-when-windows-start
https://stackoverflow.com/questions/7490249/inno-setup-how-can-i-make-my-program-run-when-a-user-logs-in-to-windows/7491472
http://www.jrsoftware.org/iskb.php?startwithwindows
If those methods don't work for some reason, perhaps a little helper executable could be created that would optionally be launched after setup and that would set things up. I think, however, that figuring out how to create a working Inno Setup script won't be a problem for you guys. :-)

**Comment by oldman777** [comment]
I suggest simply remove from the installer the forced inclusion of these settings:

1-Start ImgDrive with Windows 
2-Change ImgDrive drive icons
3-Show ImgDrive in system tray 
4-Shell extensions 
5-File association 

After installation, anyone can choose in the settings what is needed for him personally.

**Comment by bovirus** [comment]
@oldman777 

I'm not agree.

I don't believe that manual settings after installation is not the right way for most of the users.

I believe that most of the option should be set in the installer, and should have a default without user changes.

**Comment by imgdrive** [comment]
@oldman777 
If disable there options, Installer version looks like another portable version. If has no better method, i will build a special version for you.

Innosetup has limited feature to custom installation, i have a idea to obsoleted innosetup, write setup in C manually which truecrypt does. 

I am keeping listen the voice of user, how they use ImgDrive, any advice is welcome. If know how most of people use ImgDrive, i will save many design&coding time, and focus my limit free time to the main target.

Sorry for my bad english, i am not native english speaker.

**Comment by oldman777** [comment]
Thank you for offering a special version for me, but any public version is suitable for me.
You're really doing just about everything that's possible very appreciated. 
I am not native english speaker too. Apparently because of this just happened miscommunication. 
I just decided to insert my two cents in the general discussion. 
Cheers.

**Comment by MatejGolian** [comment]
I think no one of us here is a native English speaker. :-)
As for the installer, I personally don't have any requirements at this point, the way it is now works good for me, but of course I'll try to help whenever I can.
Maybe it's not a good idea, but perhaps this issue could be approached differently as well. Opening the settings dialog right after installation or upon first run could perhaps be a compromise. That way everyone could instantly set up ImgDrive the way the want. Granted, it wouldn't be part of the installer, but I think that for all purposes it would work just as good.

**Comment by imgdrive** [comment]
Here is the new setup UI:
![image](https://user-images.githubusercontent.com/19568093/43358758-46baa784-92c9-11e8-8c03-9da2bd967447.png)

After click "I accept the license terms" then:
![image](https://user-images.githubusercontent.com/19568093/43358768-68ba8854-92c9-11e8-93f6-1d3fc68cb5b9.png)

**Comment by oldman777** [comment]
Excellent! Thank you. 

Also, add checkboxes "File associations" and "Check for updates automatically".
It's all together will show additional features ImgDrive at the beginning of the installation.
And it also will satisfy users who are wary of software, which introduces additional changes to the OS without advance notice.

And maybe to replace in the first window the name of the button "Install" to "Next", or something like that.

**Comment by imgdrive** [comment]
@oldman777 
[ImgDrive_setup_demo.zip](https://github.com/dvdforge/imgdrive_translations/files/2238668/ImgDrive_setup_demo.zip)

![image](https://user-images.githubusercontent.com/19568093/43365423-65cc9164-935f-11e8-9440-a90cbe964a46.png)

This is just a demo to show the new setup UI, still in developing.

**Comment by oldman777** [comment]
Just tested DEMO.exe. 
This version of the installer even better than I could imagine earlier. 
I look forward to the final release.  
Thank you!

**Comment by imgdrive** [comment]
@oldman777 
Hi, please try this new installer:
https://download.yubsoft.com/ImgDrive_1.6.0.exe

**Comment by oldman777** [comment]
Hi, The installer looks fine, but if do not enable the shell extension in the installer, then afterwards, it's impossible to enable it in the settings. And a lot of lines without translation.

**Comment by oldman777** [comment]
> And a lot of lines without translation.  

I did not notice the updates in ImgDrive_RUS.ini. Already translated.

**Comment by imgdrive** [comment]
> Hi, The installer looks fine, but if do not enable the shell extension in the installer, then afterwards, it's impossible to enable it in the settings. 
Will add a Install/Uninstall shell extension button in Integration page.

> And a lot of lines without translation.
Do you mean the setup dialog? i am sort out the strings need be translated. Do you think it's necessary to translate the selected strings below:
![image](https://user-images.githubusercontent.com/19568093/43637152-c4f3be7a-9746-11e8-80d4-e180e1c172c8.png)

**Comment by oldman777** [comment]
> Do you mean the setup dialog? i am sort out the strings need be translated. Do you think it's necessary to translate the selected strings below:  

To translate the selected strings not needed - These machine instructions very few people interested. 
And for who interested can understand in English.  
Need to tranlate this. Because after the installation ImgDrive turns out in English: 

![2018-08-03_133226](https://user-images.githubusercontent.com/28647829/43638501-d851be42-9721-11e8-8dfa-44acec95dbb3.jpg)

**Comment by oldman777** [comment]
> Hi, The installer looks fine, but if do not enable the shell extension in the installer, then afterwards, it's impossible to enable it in the settings.
> Will add a Install/Uninstall shell extension button in Integration page. 

If the installation process does not checked "Integrate into shell": 

![2018-08-03_1315381](https://user-images.githubusercontent.com/28647829/43638916-2dae13e4-9723-11e8-8e3c-7ffc7ff28a39.jpg) 

When ImgDrive already installed, in the options already checked "Enable shell extensions",  
but in the context menu Windows it does not appear. 

![2018-08-03_134937](https://user-images.githubusercontent.com/28647829/43639368-c2cfb5e4-9724-11e8-9c75-b1f118a4e96b.jpg)

**Comment by imgdrive** [comment]
It doesn't check whether the shell extension is installed, will be fixed later.

**Comment by imgdrive** [comment]
or replace the current "Enable shell extensions" with "Integrate into shell"?

**Comment by oldman777** [comment]
Yes, use the same phrases in both places, it's reasonable.

**Comment by imgdrive** [comment]
@oldman777 
"Integrate into shell" has implemented in v1.6.1
http://download.yubsoft.com/ImgDrive_1.6.1.exe

**Comment by oldman777** [comment]
Just tested, perfect. Thank you.
