### ISSUE TITLE
The 'Unmount' Menu Entries Shoud Be Grayed Out in Certain Cases

### ISSUE THREAD

**Issue by MatejGolian** [dvdforge/imgdrive_translations#25]
Similarly to how the Mount menu item in the File menu behaves, I think that the Unmount item should be grayed out (disabled) if there are no drives enabled or if no drive has been selected in the list of added drives. Likewise, the Unmount All Drives item should be grayed out if no drives have been enabled. The tray menu item behaves like this already, so it would be nice if the item in the File menu behaved like that as well.

**Comment by imgdrive** [comment]
please re-download an try: http://download.yubsoft.com/ImgDrive_1.4.6.exe

**Comment by MatejGolian** [comment]
Thank you for being so quick. It seems OK so far. Perhaps one more thing.
Currently when you right click on a drive, in the context menu that appears the Unmount item is grayed out if there is nothing mounted on to that particular drive. Could you make the corresponding File menu entry behave in the same way too? Hope it doesn't complicate stuff.

**Comment by imgdrive** [comment]
please try: http://download.yubsoft.com/ImgDrive_1.4.7.exe

**Comment by MatejGolian** [comment]
Thank you, it works perfect. :-)
