### ISSUE TITLE
Dealing with Associated File Types If no Drive Is Enabled

### ISSUE THREAD

**Issue by MatejGolian** [dvdforge/imgdrive_translations#26]
Currently, if no drives have been enabled and you double click a file type associated with ImgDrive, nothing happens. Maybe ImgDrive could do one of these 2 things instead:
1. It could display a message saying  something like that "No drives are currently enabled. Please, enable at least one drive before mounting an image". Or
2. It could automatically enable one drive in the settings and than mount the image in question.
The 3rd alternative is of course to leave things as they are now. This is just a suggestion to consider - do as you see fit. :-) I don't know how it all works - maybe that second option is tricky to implement anyway.

**Comment by imgdrive** [comment]
implemented the second option

please try: http://download.yubsoft.com/ImgDrive_1.4.7.exe

**Comment by MatejGolian** [comment]
I only did a very quick test with 2 ISO images, but from what I can tell, it works absolutely fabulous. :-) Many thanks, ImgDrive is getting better and better with every release. :-)

**Comment by imgdrive** [comment]
You are welcome, you really help me a lot to make ImgDrive better. :-)
