### ISSUE TITLE
[STRING] 73,74,75,76 - where it is used?

### ISSUE THREAD

**Issue by oldman777** [dvdforge/imgdrive_translations#27]
Hi, I can not find it in ImgDrive GUI to check the correctness of the translation. Thanks. 

[STRING]
73=Session %d
74=Track %d
75=Session
76=Track

**Comment by imgdrive** [comment]
They are prepare for the future, will be used in disc file explorer dialog.
![zzz](https://user-images.githubusercontent.com/19568093/42831577-48c8c228-8a21-11e8-91f3-876ee2951efc.png)

**Comment by oldman777** [comment]
Got it. Thanks.
