### ISSUE TITLE
ImgDrive 1.5.0 beta

### ISSUE THREAD

**Issue by imgdrive** [dvdforge/imgdrive_translations#28]
Installer version (.exe): http://download.yubsoft.com/ImgDrive_1.5.0.exe
Portable version x64: http://download.yubsoft.com/ImgDrivePortable_x64.exe
Portable version x86: http://download.yubsoft.com/ImgDrivePortable_x86.exe
Portable version x86/x64 in one: http://download.yubsoft.com/ImgDrivePortable.exe

change log:
* update language files
* using same drive files for vista/win7/win8/...
* ImgDrivePortable.exe: x86/x64 in one for portable version, which LZMA compress ImgDrivePortable_x86.exe and ImgDrivePortable_x64.exe, appended to setupldr, very simple wrapper. Avira false positive here :-(
* [Issue](https://github.com/dvdforge/imgdrive_translations/issues/26): sleep 3 seconds when mounting with no drive enabled, it seems ImgDrive will not work if don't delay some time in this case.

to do:
* MDS/MDX v2.0: very complicated, v2.0 uses many encryptions, AES256, twofish, CRC32, i have successful got the decoded data by dll injection, but it not a good idea to use in product. Need more free time to continue.
* CUE: multiple-file/multiple-session support

**Comment by oldman777** [comment]
During the installation, a red OS warning appeared that the driver does not have a digital signature, 
or something like that. This was the first time in this version only.

**Comment by imgdrive** [comment]
thank you for the feedback, fixing...

**Comment by oldman777** [comment]
File associations can not be enabled via ImgDrive settings. 

PS: From the third time all the same it was possible.

**Comment by imgdrive** [comment]
plz try: http://download.yubsoft.com/ImgDrive_1.4.9.exe

have tested in win7, no red OS warning here.

**Comment by imgdrive** [comment]
For the file associations issue:
could you check the registry default value of: HKEY_CLASSES_ROOT\.xxx\, replace xxx with the file extension you have processed.

![image](https://user-images.githubusercontent.com/19568093/42893280-763af01c-8ae6-11e8-9da4-d17f4a27c5b8.png)

**Comment by bovirus** [comment]
Also for me no red OS warning (OS Windows 7 64bit)
Tested ImgDrive 1.4.8/1.4.9.

**Comment by oldman777** [comment]
1.4.9 no red OS warning.  
It's possible to add updated today ImgDrive_RUS.ini?

**Comment by imgdrive** [comment]
@oldman777 
updated, download it again: http://download.yubsoft.com/ImgDrive_1.4.9.exe

**Comment by oldman777** [comment]
Tested OK. Thanks.

**Comment by imgdrive** [comment]
public release v1.5.0

add a registration dialog for newbies:
[DIALOG_16]
0=Registration
1=Register
2=Cancel
3=Help
4=Paste the key which you received into the box below.

[STRING]
78=Registration...
79=Thanks for registering!
80=The registration key you input is incorrect.

**Comment by oldman777** [comment]
RUS updated for 1.5.0.

**Comment by oldman777** [comment]
AVIRA still blocks the ImgDrivePortable.exe.

**Comment by bovirus** [comment]
@dvdforge 

English language updated
Version from 1.4.7 to 1.5.0.
Please everytime that you update language file please update also version inside

Italian language updated

**Comment by oldman777** [comment]
I sent "ImgDrivePortable.exe" to AVIRA analysis system: 
https://analysis.avira.com/en/submit 
After verification is excluded from the virus database. Now it's listed as clean.

**Comment by imgdrive** [comment]
Has uploaded with latest language files: http://download.yubsoft.com/ImgDrive_1.5.0.exe

**Comment by oldman777** [comment]
Hi. Now the following lines are used: 

```
[DIALOG_50]
3=A new version of %s is available!
4=%s %s is now available - you have %s. Would you like to download it now?  
```

These lines are also needed for some other purpose? 

```
[DIALOG_50]
14=A new version of %s is available!
15=%s %s is now available - you have %s.
```

**Comment by imgdrive** [comment]
@oldman777 
wow, i forget to remove these, had removed, new installer had uploaded to:
https://download.yubsoft.com/ImgDrive_1.5.0.exe

**Comment by oldman777** [comment]
A couple more issues. 
**1-Cropped phrase:** 

```
[DIALOG_6]
4=Мы будем очень благодарны, если вы сможете сообщить об этой проблеме, чтобы 
```
instead
```
[DIALOG_6]
4=Мы будем очень благодарны, если вы сможете сообщить об этой проблеме, чтобы помочь нам улучшить ImgDrive 
```
![2018-07-21_173145](https://user-images.githubusercontent.com/28647829/43036576-f8e016aa-8d0c-11e8-8777-21f1253a808d.jpg)

And after pressing "Report this Issue", nothing happens. So it should be? 

**2-Where can I see [DIALOG_5], to check the translation?**

**Comment by imgdrive** [comment]
dialog_5 will be shown when mount a image file at local network which need login with user/pwd. 

I copy and paste the Russian string to resource edit, here is the UI:

![image](https://user-images.githubusercontent.com/19568093/43037592-50dfedec-8d41-11e8-91ff-9374d56893bf.png)

**Comment by imgdrive** [comment]
How about to change layout of [DIALOG_6] to:
![image](https://user-images.githubusercontent.com/19568093/43037654-1ef06d2e-8d42-11e8-8890-d3b7fee719b0.png)?

**Comment by oldman777** [comment]
Cropped phrase [DIALOG_5]
`4=&Имя пользоват` 
instead
`4=&Имя пользователя` 

A new [DIALOG_6] is even better. 

**I propose to replace the string** 
[STRING]
`33=Image `
with 
`33=Image Path`  

![2018-07-21_184224](https://user-images.githubusercontent.com/28647829/43037582-4af5c19c-8d17-11e8-963b-197f898973d3.jpg)

**Comment by imgdrive** [comment]
From the report,  >90% reports were caused by:
1. cannot find the .wav/.ape/.flac... data file listed in .cue
2. not a 16-bit/44.1kHz audio files, cannot mount as Audio CD
3. MDS v2.0

Maybe implement in future:
for case 1,  let the user to select the image manually (show a dialog list all support image file under the .cue file).

for case 2, prompt user doesn't support this format, let the user convert it to 16-bit/44.1kHz...

for case 3, eh, hard nut to crack

**Comment by oldman777** [comment]
```
[STRING] 
49=Burn Image File
52=Burn
60=Erasing disc
61=Formatting disc 
```
are needed for what the future features?

**Comment by imgdrive** [comment]
> [STRING] 
> 49=Burn Image File
> 52=Burn
> 60=Erasing disc
> 61=Formatting disc 
Yes

**Comment by imgdrive** [comment]
> And after pressing "Report this Issue", nothing happens. So it should be?

I am not sure whether it's annoy to show a box again after sent the report successfully.

**Comment by oldman777** [comment]
> I am not sure whether it's annoy to show a box again after sent the report successfully. 

Then everything is fine.
