### ISSUE TITLE
ImgDrive todo - Please submit your feature request here

### ISSUE THREAD

**Issue by imgdrive** [dvdforge/imgdrive_translations#29]
ImgDrive was first public release at May 10,  2016, spend me much time to code it, eat the dog food. very happy to look it getting better.

ImgDrive is not perfect, please submit your feature request here, i take your suggestions and feedbacks very seriously and try to implement when its possible.

- Support mount .cue with multiple audio files 
- Support mount .cue with multiple session
- Support mount .mds/.mdx version 2.0

**Comment by oldman777** [comment]
Support mount **.mdx**. 
I tried to open .mdx, and to the same message without Russian translation, and in any language the same.

![2018-07-22_195932](https://user-images.githubusercontent.com/28647829/43048076-6c344350-8dea-11e8-96b3-0d978013e77a.jpg)

**Comment by oldman777** [comment]
Propose to add the feature of **ScanDisk** to check the quality of the disc. 
I've been using a Nero CD-DVD Speed for these purposes more than ten years, 
because there is no good substitute for this. 
http://www.free-codecs.com/download/nero_dvd_speed.htm 
This can be placed in the "Properties" window, as the fourth tab. 
To do something like this, if it is possible at all.

![2018-07-23_130856](https://user-images.githubusercontent.com/28647829/43071546-d0b052e2-8e7b-11e8-9947-bf3d3fb850ae.jpg)

**Comment by imgdrive** [comment]
@oldman777
it seems only make sense for real disc, i will hook the SCSI command to see what does it do internal.

**Comment by oldman777** [comment]
I meant to do ScanDisk for a real disk, not for a virtual one.

**Comment by Jarek63** [comment]
Please consider adding an option image to the context menu of the file: Unmount and Hide unmounted drives

**Comment by oldman777** [comment]
`Please consider adding an option image to the context menu of the file: Unmount and Hide unmounted drives` 
This is a great idea! 

I do not understand the purpose in the context menu of the file `Mount to &%C: - %s` after the image is already mounted. The image just re-mounted.   Maybe it is replaced by `Unmount` , or to delete.

**Comment by oldman777** [comment]
Suggest adding the line "Autorun" to the context menu of the main window. 

![2018-07-26_00531](https://user-images.githubusercontent.com/28647829/43231617-d0771b16-9075-11e8-8e2e-6e3b8d595313.jpg)

**Comment by imgdrive** [comment]
@Jarek63 @oldman777 
> Please consider adding an option image to the context menu of the file: Unmount and Hide unmounted drives
I am not sure if i understand correctly, here is the new context menu with image:
![imgdrive158](https://user-images.githubusercontent.com/19568093/43238859-94f1c670-90c2-11e8-84d2-949c25f9c98e.jpg)

Do you mean add the "Hide unmounted drives" in the File menu?

**Comment by imgdrive** [comment]
@oldman777 
> I do not understand the purpose in the context menu of the file Mount to &%C: - %s after the image is already mounted. The image just re-mounted. Maybe it is replaced by Unmount , or to delete.

Yes, i'm also confused, not sure whether it make sense to show the current image path.

**Comment by imgdrive** [comment]
@oldman777 
> Suggest adding the line "Autorun" to the context menu of the main window.

Click "Autorun", then run the application in autorun.inf? or Autoplay the disc(for audio cd/dvd/bd) ?

**Comment by oldman777** [comment]
> Click "Autorun", then run the application in autorun.inf? or Autoplay the disc(for audio cd/dvd/bd) 

Autorun to call this window. 

![2018-07-26_091441](https://user-images.githubusercontent.com/28647829/43244892-11a24586-90b5-11e8-9cad-b66ed8e6713e.jpg)

**Comment by oldman777** [comment]
> I do not understand the purpose in the context menu of the file Mount to &%C: - %s after the image is already mounted. The image just re-mounted. Maybe it is replaced by Unmount , or to delete.  

> Please consider adding an option image to the context menu of the file: Unmount and Hide unmounted drives
> I am not sure if i understand correctly, here is the new context menu with image:

I meant in the context menu of Windows (Shell extension), when the image is mounted, 
to replace "Mount to &%C: - %s " to "Unmount &%C: - %s ". 

![2018-07-26_00531o_cr](https://user-images.githubusercontent.com/28647829/43245774-2e1b6884-90b8-11e8-940d-0cca4c0324c4.jpg)

**Comment by Jarek63** [comment]
I would like to see these options not only in the program menu, but also in the context menu of the image file (.iso, .cue ...).

**Comment by oldman777** [comment]
**Jarek63**
> I would like to see these options not only in the program menu, but also in the context menu of the image file (.iso, .cue ...).

To be honest, I did not quite understand - Why do you need to "Hide unmounted drives"  in menus? 
In my understanding, often used functions are displayed in the menu, 
and rarely used are hidden in the "Options".  
I can not imagine a situation in which I will need "Hide unmounted drives" several times a day.
In my opinion what is already there in the "Options" enough.

![2018-07-27_170333](https://user-images.githubusercontent.com/28647829/43325768-166be570-91c0-11e8-8647-47e0f950e19e.jpg)

**Comment by Jarek63** [comment]
I was concerned about the maximum comfort of using the program. It all depends on how often you use it. But of course this was just a suggestion on my part. You can open the main program window and use the menu functions.

**Comment by oldman777** [comment]
> Propose to add the feature of **ScanDisk** to check the quality of the disc.
> **This can be placed in the "Properties" window, as the fourth tab.**  

I have not accurately expressed earlier about - **"This can be placed in the "Properties" window"**.  
"Properties" window applies only to the virtual drive. 
I would like the same window for real disks, with the same three tabs, plus the "Scandisk" described above. 
It can be called something like a "CD / DVD manager" and placed in the "Tools" menu, or somewhere else.
Is it even possible? 

![2018-07-26_005319](https://user-images.githubusercontent.com/28647829/43359163-a4760c1a-92a6-11e8-9063-dacd29b7cecc.jpg)

**Comment by oldman777** [comment]
Move "Create ISO Image" and "Copy Disk"  from the "File" menu 

![2018-07-2](https://user-images.githubusercontent.com/28647829/43364234-ff9a8d46-931e-11e8-8e91-da3cae7cc84b.jpg)

in the "Tools" menu.  It seems it will be more suitable. And "Options" move to the bottom of the menu "Tools", through the separator.

![2018-07-26_cr_cr](https://user-images.githubusercontent.com/28647829/43364236-11bf638e-931f-11e8-99f9-34a89f3bdc7e.jpg) 

PS: Typically, the most commonly used features in top, and most rarely used, lower in the menu.

**Comment by imgdrive** [comment]
> I have not accurately expressed earlier about - "This can be placed in the "Properties" window".
"Properties" window applies only to the virtual drive.
I would like the same window for real disks, with the same three tabs, plus the "Scandisk" described above.
It can be called something like a "CD / DVD manager" and placed in the "Tools" menu, or somewhere else.
Is it even possible?

i am willing to add this feature, but may has no enough time to implement it. 

CDSpeed works like a charm, ImgDrive focus on virtual images,  if possible, i prefer to add a plugin interface which support add a menu item for CDSpeed.exe.

**Comment by imgdrive** [comment]
> Autorun to call this window. 
![2018-07-26_091441](https://user-images.githubusercontent.com/28647829/43244892-11a24586-90b5-11e8-9cad-b66ed8e6713e.jpg)

This is a system dialog, i guess, Microsoft guys dislike to export this API as usual :-)

i will evaluate this feature when implements "Disable Autorun" feature.

**Comment by oldman777** [comment]
> i am willing to add this feature, but may has no enough time to implement it.
> CDSpeed works like a charm, ImgDrive focus on virtual images, if possible, i prefer to add a plugin interface which support add a menu item for CDSpeed.exe. 

Got it. Then the feature request about real disks is closed.  

> This is a system dialog, i guess, Microsoft guys dislike to export this API as usual :-) 
> i will evaluate this feature when implements "Disable Autorun" feature.  

Then autorun is also not needed.  Autorun feature request is closed too.

**Comment by oldman777** [comment]
1.6.0 not fixed, message without Russian translation, and in any language the same. 

![4304807](https://user-images.githubusercontent.com/28647829/43631425-d6ce1b26-970b-11e8-932a-03406cc6409c.jpg)

**Comment by oldman777** [comment]
1.6.0 not fixed,  in the context menu of Windows (Shell extension), when the image is mounted,
to replace "Mount to &%C: - %s " to "Unmount &%C: - %s ".  

![43245774-](https://user-images.githubusercontent.com/28647829/43632090-ccd2ff7c-970d-11e8-8e22-443bb1be75b2.jpg)

**Comment by imgdrive** [comment]
"Mount to G: %s" the %s is the current mounted image location, not the current selected file's.
when users right click a image file, what they want to do is mount that file.

i'll think this issue again...

**Comment by oldman777** [comment]
> "Mount to G: %s" the %s is the current mounted image location, not the current selected file's.
> when users right click a image file, what they want to do is mount that file.
> 
> i'll think this issue again...

 Let it be as it is. I had mixed Russian and English in my head. 
The phrase "Mount to"  must be replaced with "Mounted to" in terms of "Already mounted", 
and everything will be fine.

**Comment by Jarek63** [comment]
In Windows XP version 1.6.5. and 1.7.0 does not install the imgdrive.dll file. The context menu option does not work.

**Comment by oldman777** [comment]
Can someone explain to me why it was necessary to possess this feature in the menu?  
And why overload the menu with completely unnecessary things? 
I mount a few dozen images a day, and for several months I do not need to turn it on or off this even once.

![2018-08-10_231340](https://user-images.githubusercontent.com/28647829/43979523-a3a2006c-9cf3-11e8-82eb-2627a9a7cd2b.jpg) 

If this feature is enabled, then all unmounted drives always are hidden automatically.  
If this feature is disabled, then all unmounted drives always are not hidden .  
Someone please describe the situation when several times a day it is necessary to turn it on or off.

**Comment by imgdrive** [comment]
@Jarek63 
please re-download: https://download.yubsoft.com/ImgDrive_1.7.0.exe

**Comment by Jarek63** [comment]
Is there a switch for silent installation of this program?

**Comment by imgdrive** [comment]
@Jarek63 
No, will add in future.

Next release will include support for MDS 2.0/MDX, CDI.

**Comment by oldman777** [comment]
> Next release will include support for MDS 2.0/MDX, CDI.

Great news, thank you.

**Comment by reyaz006** [comment]
Not exactly a feature request.

I have a blu-ray video iso which is taken from torrent and it's downloaded by 99,99 %. I've checked many times and it appears that the last ~2 megabytes of data is absent. When checking other similar blu-ray iso, I've noticed the last bits of data contain mostly 00 bytes, but also appear to hold some meta data.

There is only about 10 kb on non-zero bytes there. I can see the following strings in hex editor:
```
SonicScenaristBD
DMV
CERTIFICATE
AACS
index.bdmv
MovieObject.bdmv
PLAYLIST
CLIPINF
STREAM
AUXDATA
BACKUP
```
There are also file names with .mpls and .clpi extensions.

It's possible to open the iso file and extract actual files - there are no issues with that. But those bits at the end of the image appear to be important. Emulation with any tool fails, and in case with ImgDrive it just crashes.

I want to ask what exactly this data is responsible for. Maybe it's names for some internal file system, maybe it contains only meta information about video streams on disc, maybe it's all about blu-ray menu with stream selection.

Also, is it possible to regenerate such information in some way to make the image work? E.g. extract all files and create a new iso file from them or something similar.

Thanks.

**Comment by imgdrive** [comment]
@reyaz006 it's possible to regenerate one, please try to extract all files to local disk, then use ImgDrive "Mount Folder...", ImgDrive will generate a new UDF 2.5 file system on the fly.

the last 512KB contains Anchor Volume Descriptor Pointers (AVDP), the last 2MB maybe contains metadata mirror file.

**Comment by seba2282** [comment]
Can I suggest create image not only in iso, but example iso, mdx and  etc to choose + options create image, like have alcohol 120% / 52%, it are: read drm, subchannels, pregape, fast skip errors with ignore read error and etc what have image creator in Alcohol; and emulation protections cd/dvd/bd in that program? It was seriously nice see that options.

**Comment by ghost** [comment]
Hello, could you support Disc Image Chef format? https://github.com/discimagechef/DiscImageChef/blob/master/DiscImageChef.DiscImages/DiscImageChef/Structs.cs

We are using it for preservation of all kinds of optical media, would be awesome to see. Version 2 which is due out sometime, will also support twin sectors and hopefully DPM for both CD and DVD.

Thank you.

**Comment by ghost** [comment]
I would like to see a feature that allows mounting BIN/CUE mixed-mode or audio-only CDs and have the CD audio tracks available as such to media players (such as foobar2000). This would mainly be useful for using or testing software that uses CD audio for playback.

**Comment by seba2282** [comment]
If about audio is saying, I don't know was that suggest or not. But I would see audio converter option here, like is in example Alcohol. But integrated not like in Alcohol with download plugin first.

**Comment by steph-nb** [comment]
Great Tool!
Creation of iso from folders via command line would be great!

Thank you.

**Comment by virox** [comment]
I'm still very much hoping for *.cue with multiple audio file support. :)

**Comment by seba2282** [comment]
I still wait on possible make images in mdx format, read dpm, pregape, fast skip error, read subchannels, etc and emulation protections cd/dvd/blu-ray and audio converter (working on protection audio too). Optionally support video converter too from discs (included with support protection read).

**Comment by Felipefpl** [comment]
Indeed, one of the features imgdrive needs the most is more support for different file formats like daemon tools has:

https://daemon-help.com/preferences/integration/

Sometimes like it happened with me we can get .bin files without a cue or maybe even .mdf files without a .mds, having support for the "main files" is also very needed.
