### ISSUE TITLE
No warning DIALOG - "The file [%s] already exists..."

### ISSUE THREAD

**Issue by oldman777** [dvdforge/imgdrive_translations#30]
I'm doing a "copy disc", creating a disk image.
I do it again, and the old image is deleted without any warning and the exact same is written instead. 
DIALOG:
`57=The file [%s] already exists. Do you want to replace the existing file? `
does not appear.

**Comment by imgdrive** [comment]
It's a bug, has fixed, need some days to release new beta.

**Comment by oldman777** [comment]
1.6.0 fixed.
