### ISSUE TITLE
The explanation in [DIALOG_9] is not displayed.

### ISSUE THREAD

**Issue by oldman777** [dvdforge/imgdrive_translations#31]
The explanation in [DIALOG_9] (Create ISO Image) is not displayed: 
```
3=Please select or drag drop a folder to create ISO image file. 
```
![2018-07-23_192318](https://user-images.githubusercontent.com/28647829/43089661-e93a5c90-8ead-11e8-8974-d3e1243a3722.jpg)

 Propose to delete the unnecessary more line in [DIALOG_9] 
`6=Volume label:`

And to add the same explanation in [DIALOG_10] (Copy Disc).  
`Please select or drag drop a folder to create ISO image file. `

**Comment by imgdrive** [comment]
I hide the string to make it more simple, it's should show to make it easy to use. Has changed to:
![image](https://user-images.githubusercontent.com/19568093/43113460-12403aa4-8f2d-11e8-93b0-d91581d9fe01.png)

**Comment by imgdrive** [comment]
For copy disc dialog, only allow to select a drive, no drag drop, and in future, will add "output .cue+.wav/.ape" feature.

**Comment by imgdrive** [comment]
One more thing: Target file vs Destination file, which one do you think is better to show in [DIALOG_9] and [DIALOG_10] ?

**Comment by imgdrive** [comment]
> Propose to delete the unnecessary more line in [DIALOG_9]
> 6=Volume label:

Had deleted, thank you :+1:

**Comment by oldman777** [comment]
> For copy disc dialog, only allow to select a drive, no drag drop, and in future, will add "output .cue+.wav/.ape" feature.

Then you're right. It is necessary to hide this in both dialogues [DIALOG_9] & [DIALOG_10], so that there will not be any confusion in the future.

**Comment by oldman777** [comment]
> One more thing: Target file vs Destination file, which one do you think is better to show in [DIALOG_9] and [DIALOG_10] ? 

I think:
`Destination image `
or
`Output image`

**Comment by oldman777** [comment]
Or: 
`Destination image file`
or
`Output image file`

**Comment by oldman777** [comment]
As a result, in the Russian translation I took as a basis, for simplicity, for two windows: 
```
Input folder 
Output image 
```

```
Input disc
Output image 
```

**Comment by dvdforge** [comment]
Have changed it to: Destination image, thank you.

**Comment by oldman777** [comment]
1.6.0 fixed.
