### ISSUE TITLE
Eject and Unmount conflict

### ISSUE THREAD

**Issue by oldman777** [dvdforge/imgdrive_translations#33]
If you click "Eject" when the image is already mounted, the image is unmounted, 

![2018-07-26_005314](https://user-images.githubusercontent.com/28647829/43230818-7b626994-9072-11e8-9191-487c4f37100b.jpg)

but looks in the address line as "Mounted".  

![2018-07-26_011301](https://user-images.githubusercontent.com/28647829/43230843-913db804-9072-11e8-90df-e54cc6e3901c.jpg)

**Comment by oldman777** [comment]
1.6.0 still not fixed.

**Comment by imgdrive** [comment]
![untitled-1](https://user-images.githubusercontent.com/19568093/43637569-184d7df8-9748-11e8-87d0-95d298150318.png)

I'll add a state image for each drive, replace the current trivial drive image .
ejected - yellow
loaded - green

**Comment by oldman777** [comment]
Well, that's fine too.

**Comment by imgdrive** [comment]
Drive state has implemented in v1.6.1
http://download.yubsoft.com/ImgDrive_1.6.1.exe

**Comment by oldman777** [comment]
Just tested, amazing. Thank you.
