### ISSUE TITLE
Error: The version of this file is incompatible with the current version of Windows.

### ISSUE THREAD

**Issue by oldman777** [dvdforge/imgdrive_translations#34]
Image MDS/MDF v 1.0, Win 7x64.  Image mounted, but when trying to use autorun, this error occurs. 
Through Alkohol 52% it is mounted and installed without problems.  
File MDS attached.

![2018-07-26_222255](https://user-images.githubusercontent.com/28647829/43284255-e50c5678-9123-11e8-8b69-6304beda6f1d.jpg)
[FLATOUT2.zip](https://github.com/dvdforge/imgdrive_translations/files/2233324/FLATOUT2.zip)

**Comment by oldman777** [comment]
1.6.0 still not fixed.

**Comment by imgdrive** [comment]
It seems ImgDrive succesfully parsed the .mds file, i need the .mdf to check why it doesn't work.

Is it a DVD or CD? do you have a torrent file to download the .mdf?

**Comment by oldman777** [comment]
It's my personal DVD. I created the image several years ago via Alcohol 52%. 
Send you via email.

**Comment by oldman777** [comment]
> Is it a DVD or CD? do you have a torrent file to download the .mdf? 

I'm still here with this torrent tried to mount "FlatOut 2". The same error. 
But the checksum is different from the way that I did.

**Comment by oldman777** [comment]
One more, now the image of "ISO" does not open. In alcohol is's OK. 
Send you via email.  

When you try to open this image, the window appears: 

![2018-08-04_162810](https://user-images.githubusercontent.com/28647829/43677013-e335fbf6-9803-11e8-863f-3db97beeb8ce.jpg)

**Comment by oldman777** [comment]
Still is in 1.6.2

**Comment by imgdrive** [comment]
Still downloading the .mds file, only 10KB/s :-(

**Comment by imgdrive** [comment]
.../fo2.zip.001.html

Is this file same with FlatOut Anthology bt file?

**Comment by oldman777** [comment]
fo2.zip.001-005 this is a multi-volume zip archive. This is my "FlatOut 2". 4.32GB total. 
You need to download all 5 parts, and after unpacking we get: FLATOUT2.MDF and FLATOUT2.MDS.

**Comment by imgdrive** [comment]
@oldman777 
It seems SETUPX.exe has wrong map(SETUPX.exe not a valid .exe file, wrong PE format), .mds should has special switch for this issue. Could you send me SETUPX.exe and setupx.dat which mounted by alocohl 52%? 

![image](https://user-images.githubusercontent.com/19568093/43678473-771ddc34-9846-11e8-9f1f-a56588215df8.png)

**Comment by oldman777** [comment]
Of course. 

SETUPX.exe and setupx.dat 

[SETUPX.zip](https://github.com/dvdforge/imgdrive_translations/files/2259638/SETUPX.zip)

**Comment by oldman777** [comment]
After the "ImgDrive" issued an error for "FlatOut 2", I ran "setup.exe",  and the installation started. 
 In the middle of the installation, a window appeared that the file was corrupted. 
I interrupted the installation, mount the image on Alcohol and the game was fully installed, found no issues.

**Comment by oldman777** [comment]
I copied FlatOut 2"  image contents via ImgDrive and after, via Alcohol, and compared the checksums. 

![2018-08-04_204724](https://user-images.githubusercontent.com/28647829/43679117-365020ae-9828-11e8-840f-b5d7097c3875.jpg)

**Comment by oldman777** [comment]
And if extract the files through ImgDrive File explorer, then checksums coincide. 

![2018-08-04_211227](https://user-images.githubusercontent.com/28647829/43679308-d3cf2066-982b-11e8-85f1-9203576079e9.jpg)

**Comment by oldman777** [comment]
For another ISO image issue, the content is not available through the Windows Explorer. 
And  through ImgDrive File explorer, also may extracted, then checksums coincide too.

**Comment by imgdrive** [comment]
please try this one: http://download.yubsoft.com/ImgDrive_1.6.3.exe

**Comment by oldman777** [comment]
1.6.3 Fixed for FlatOut 2 only. 
For other ISO still blank window: 

![43677](https://user-images.githubusercontent.com/28647829/43685838-1de20e6a-98c3-11e8-9100-7bf7fbfcf459.jpg)

**Comment by imgdrive** [comment]
Still downloading the ISO.zip, 12KB/s, need about two days to finished.

**Comment by imgdrive** [comment]
![image](https://user-images.githubusercontent.com/19568093/43687943-ba5addf0-9911-11e8-8ba4-55228b5642de.png)

I can mount it successfully here. Whether doesn't File Explorer and Sector View works? I think this is the same issue with "Mount Folder"

**Comment by oldman777** [comment]
File Explorer and Sector View works fine for this ISO. I think too, this is the same issue with "Mount Folder".

**Comment by oldman777** [comment]
Maybe the issue is that I have a Russian OS.
The ImgDrive does not have what kind of Unicode, or something like that. 
(I do not understand much about this).

**Comment by imgdrive** [comment]
Please try: https://download.yubsoft.com/ImgDrive_1.6.5.exe

After trace some the CD-ROM command, i found several silly bug which old ImgDrive exist. Old ImgDrive doesn't handle SCSI_GET_EVENT_STATUS right at all, v1.6.5 add fixed code. But one thing if the Computer has some program which send SCSI_GET_EVENT_STATUS all the time, it will cause Windows Explorer has no opportunity to known a new media arrival.

And it seems it open the switch: "Hide Unmounted Drivers", this issue doesn't exist.

**Comment by oldman777** [comment]
I'm not sure that I understood everything correctly, but I still have an empty window for 1.6.5.
