### ISSUE TITLE
It is impossible to "mount a folder".

### ISSUE THREAD

**Issue by oldman777** [dvdforge/imgdrive_translations#36]
When using "Open" in imgdrive context menu and "My Computer", "Open", an empty field only. 
Possible to open via "File explorer" and "Sector wiever" only.

**Comment by oldman777** [comment]
When you try to open the folder, the window appears: 
Still is in 1.6.2.

![2018-08-04_162810](https://user-images.githubusercontent.com/28647829/43677024-0f269a86-9804-11e8-9ff5-53acc79f49c6.jpg)

**Comment by imgdrive** [comment]
For every folder?

I have met this issue several times while mounting a .iso files, it can view the file in File Explorer and Sector Viewer, but cannot open in Windows Explorer, but after mount some other files, then everything is OK, a weird issue, i will review source code to see where goes wrong.

**Comment by oldman777** [comment]
Yes, for every folder.

**Comment by oldman777** [comment]
For what purpose at all do need the feature "Mount folder"?

**Comment by imgdrive** [comment]
Rarely.

maybe mount DVD/Blu-ray folder as a disc, some players are not allowed to play movie under a folder.
or
to quick test disc authoring, especially when the disc has lots of data.

in future, will support mount a audio folder as Audio CD, then do not need .cue, just drag a folder to ImgDrive.

**Comment by oldman777** [comment]
Got it. Thanks.

**Comment by imgdrive** [comment]
please check whether this issue still exist in version 1.6.3:
http://download.yubsoft.com/ImgDrive_1.6.3.exe

**Comment by oldman777** [comment]
1.6.3 for "Mount folder" for any folder still blank window:  

![43677](https://user-images.githubusercontent.com/28647829/43685861-7f63343e-98c3-11e8-96a3-d3ad125f009b.jpg)

**Comment by imgdrive** [comment]
Please try v1.6.5: https://download.yubsoft.com/ImgDrive_1.6.5.exe

**Comment by bovirus** [comment]
@dvdforge 

Thanks for the new version.
Could be possible to translate the operation messages like

Extract
Set autorun

etc?

**Comment by imgdrive** [comment]
@bovirus 
Will add those strings in future, it's hard-coded in source code now.

if the new installer goes well after released, i will sort out these strings.

**Comment by oldman777** [comment]
I still have an empty window for 1.6.5.

**Comment by imgdrive** [comment]
Wow, this is the biggest lady bug i ever met.

**Comment by oldman777** [comment]
It can be a conflict with the drivers "Alcohol"?

**Comment by imgdrive** [comment]
If Alcohol is running, please exit Alcohol, and check whether it's OK.

**Comment by oldman777** [comment]
Running Alcohol or not, it is still impossible to mount the folder. 
I meant that the drivers "Alcohol" installed in the system can have to do with this?

**Comment by imgdrive** [comment]
I don't think so, bad design to do TEST_UNIT_READY/GET_EVENT_STATUS in kernel.

Whether works if open "Hide unmounted drives"?

**Comment by oldman777** [comment]
> Whether works if open "Hide unmounted drives"? 

Not worked.

**Comment by imgdrive** [comment]
Weird

whether works to mount plaza-the.station.iso if open "Hide unmounted drives"?

**Comment by oldman777** [comment]
Did I understand correctly? 

![2018-08-07_123907](https://user-images.githubusercontent.com/28647829/43768139-51256f92-9a3f-11e8-8847-d25d80699dd4.jpg)  

![2018-08-07_124007](https://user-images.githubusercontent.com/28647829/43768150-55de567a-9a3f-11e8-9ecc-5b9e395017f2.jpg)  

![2018-08-07_124108](https://user-images.githubusercontent.com/28647829/43768164-5b7cdee4-9a3f-11e8-8b32-89db4565ecb9.jpg)

**Comment by imgdrive** [comment]
Yes.

Is this issue only happen for this iso and "Mount Folder"?

And the MD5 of the plaza-the.station.iso is: 21CDFBD9A53951ABFE89527542943100 ?

**Comment by imgdrive** [comment]
I can reproduce this issue after installed Alcohol 52% in vmware, thank u.

**Comment by oldman777** [comment]
> Is this issue only happen for this iso and "Mount Folder"? 

Yes.

> And the MD5 of the plaza-the.station.iso is: 21CDFBD9A53951ABFE89527542943100 ?  

And, yes. 

plaza-the.station.iso
CRC-32: f27e6b72
   MD4: 94ab30acf84ea211bde5b936e16e11f2
   MD5: 21cdfbd9a53951abfe89527542943100
 SHA-1: e9ac4863957c834a2f0617258f85ddae044dd843

**Comment by oldman777** [comment]
I closed issue https://github.com/dvdforge/imgdrive_translations/issues/34 
Mount Folder and station.iso this is the same issue.

**Comment by oldman777** [comment]
Found two more ISO images with the same issue.

**Comment by imgdrive** [comment]
After done many tests, i found this issue was caused by sptd.sys. If has Alcohol or Daemon tools installed, will change READ DISC INFO behavior, the INPUT was changed to OUTPUT, if hook the driver stack:
udfs -> stpd
it should be:
udfs -> storport

BTW: Even you uninstalled Alcohol, the sptd.sys/dtproscsibus.sys still there and in working, after delete it manually and reboot, then everything is OK.

**Comment by imgdrive** [comment]
sptd.sys is mysterious, the file is encrypted, and dislike to be uninstalled, it works like a black hole. 

I am curious whether Alcohol support Windows 10, in order to support Windows 10, need submit your driver to Microsoft hardware dashboard to sign a driver, if you submit a encrypted driver which as sptd.sys does, Microsoft will refuse.

I will try to find a workaround for this issue...

**Comment by imgdrive** [comment]
@oldman777 
latest [v1.7.0 beta](https://download.yubsoft.com/ImgDrive_1.7.0.exe)  doesn't fix this issue, still finding the solution...

**Comment by oldman777** [comment]
Got it, thanks.

**Comment by oldman777** [comment]
ImgDrivePortable_x64_1.7 - no issue for station.iso.

**Comment by oldman777** [comment]
For ImgDrive_1.7.0.exe  - no issue for station.iso and Mount Folder.

**Comment by imgdrive** [comment]
@oldman777 
I have just tested this, it seems disappear indeed, i am sure this issue exist with the debug build yesterday, weird.

I don't know what sptd.sys does internal, but this issue is really a biggest weird issue i ever meet. No matter what, i am very happy it's disappear, hope it's never come back :-)

**Comment by oldman777** [comment]
We leave this issue open to check in future versions. Thank you.
