### ISSUE TITLE
Delete [STRING] Entry #19, If Not Needed

### ISSUE THREAD

**Issue by MatejGolian** [dvdforge/imgdrive_translations#38]
This isn't anything crucial as it does not add any new features, but it might be worth doing to keep things nice and clean for the future.
If I'm not mistaken, string number 19 in the [STRING] section no longer has a purpose. Before it was the text of the item that disabled all ImgDrive drives, but that has since been replaced by a simple 0. If it's not too much work, perhaps this string could be removed from the language files. The other strings could than be renumbered. Of course, this would mean that you would have to change the numbers of the referenced strings in the ImgDrive source code as well.
As I wrote, it's not all that important and it may not be worth it (I don't know how much work it would require), so it's up to you as always. I suggested it because I think that keeping outdated stuff in the files makes things messy in the long run.

**Comment by imgdrive** [comment]
Will remove it tomorrow, thank you!

**Comment by imgdrive** [comment]
https://download.yubsoft.com/ImgDrive_1.7.0.exe

reuse 19 as 82
change 81 to 12

**Comment by MatejGolian** [comment]
Seems good, thanks. :-)
