### ISSUE TITLE
ImgDrive 1.7.0 Beta 2

### ISSUE THREAD

**Issue by imgdrive** [dvdforge/imgdrive_translations#39]
Installer Version: https://download.yubsoft.com/ImgDrive_1.7.0.exe
Portable Version: https://download.yubsoft.com/ImgDrivePortable_1.7.exe

**Comment by oldman777** [comment]
ImgDrivePortable_1.7 

![2018-08-10_205018](https://user-images.githubusercontent.com/28647829/43973085-19c94b84-9cdf-11e8-9576-980e89347807.jpg)

**Comment by imgdrive** [comment]
It's false positive, ImgDrivePortable_1.7.exe is simple wrap for ImgDrivePortable_x86.exe and ImgDrivePortable_x64.exe.

Please try this for x64 OS version: https://download.yubsoft.com/ImgDrivePortable_x64_1.7.exe

**Comment by oldman777** [comment]
ImgDrivePortable_x64.exe. is clean. 

Windows for driver update with no Russian translation.

**Comment by oldman777** [comment]
> Windows for driver update with no Russian translation.

Removed 1.6.exe, and now everything is fine with the translation.
