### ISSUE TITLE
Let ImgDrive to support new file type

### ISSUE THREAD

**Issue by imgdrive** [dvdforge/imgdrive_translations#40]
Please submit the file type you want to ImgDrive to support, we take your suggestions and feedback very seriously and try to implement when its possible.

If you have some internal documentation/source code about the file, welcome to send us, we will list you at: http://www.yubsoft.com/imgdrive/acknowledgments.htm, and send a unique lifetime key for you.

Current unsupported file types:
- .bwt - BlindWrite
- .b5t/.b6t - BlindRead

File types that are working in progress:
- .mdx - daemon tools/alcohol 120%
- .cdi - DiscJuggler
- .ASHDISC - Ashampoo Burning Studio

**Comment by oldman777** [comment]
**.img** - This is rare, but yesterday I had to use another software for this.

**Comment by imgdrive** [comment]
@oldman777 
Whether ImgDrive works if change file extension to .iso?

**Comment by oldman777** [comment]
Also Unsupported format for .iso.

**Comment by oldman777** [comment]
**dvdforge** send via email to you.
