### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by imgdrive** [dvdforge/imgdrive_translations#41]
I am rewrite mount engine, to easy support new image format. Current progress :

- [done] Support for *.cdi image files (Instanct Copy)
- [done] Support for *.pdi image files (DiscJuggler)
- [done] Support for *.bwt image files (BlindWrite 4)
- [done] Support for *.b5t/*.b6t image files (BlindWrite 5/6/7)
- [done] Support for *.mdx image files (Alcohol 120%/Daemon Tools)
- [todo] Rewrite the mount engine
- [todo] Support multi-file cue

**Comment by oldman777** [comment]
Good work. Thank you.
