### ISSUE TITLE
Why after deleting ImgDrive in the registry there are so many entries?

### ISSUE THREAD

**Issue by oldman777** [dvdforge/imgdrive_translations#42]
Why after deleting ImgDrive in the registry there are so many entries? 
Another similar software creates up to five records maximum.   
I did a search in the registry for the word ImgDrive and this is only part of what I saw:

![2018-10-05_102454](https://user-images.githubusercontent.com/28647829/46522735-439adf80-c88c-11e8-9a24-084f1d0ce650.jpg)  

![2018-10-05_103109](https://user-images.githubusercontent.com/28647829/46522746-4a295700-c88c-11e8-86a8-97a50ff81349.jpg)

**Comment by imgdrive** [comment]
Thank u, i will check this issue when have finished the new cue-sheet module.

**Comment by imgdrive** [comment]
After a long long time, this issue finally fixed in v2.0.1.4: 
https://www.yubsoft.com/_ad/news.do?id=54

When update ImgDrive, also will clean the garbage registry entries.
