### ISSUE TITLE
CUE/BIN Audio Images Not Working

### ISSUE THREAD

**Issue by MatejGolian** [dvdforge/imgdrive_translations#43]
I don't know why, but audio CD images in CUE/BIN format don't work for me.
If this feature has not been implemented yet, perhaps you could add it once you rewrite the engine, if that's possible.
Hope that all's well with you BTW as there hasn't been an update in a fairly long time. :-)

**Comment by imgdrive** [comment]
Thank you, i am well, just don't have enough time to develop ImgDrive these days, have to work on some other projects to bring home the bacon.

I am still thinking/designing new CUE feature in my spare time, it's a bit complicate to support multi-file CUE feature for me, current has 80% completed.

I have about 3 hours a day to develop ImgDrive next month, can't promise when to release new version, will notify you when release new version.
