### ISSUE TITLE
possible memory leak or memory cache problem..

### ISSUE THREAD

**Issue by Nerboruto** [dvdforge/imgdrive_translations#44]
after using an isz image..
in windows 10 allocated memory is 1.5gb
when I unmount the virtual disk, the memory returns to normal at 1.0gb. 
in task manager i don't see  anything...

**Comment by imgdrive** [comment]
could you upload the .isz image to https://filecloud.me/ ? 

send the url to support@yubsoft.com, i will only use this image as test purpose.

**Comment by imgdrive** [comment]
can not reproduce this issue here.
