### ISSUE TITLE
Autorun+automount setting on system startup

### ISSUE THREAD

**Issue by ClockworkBastard** [dvdforge/imgdrive_translations#50]
ImgDrive being extremely tiny and portable is a brilliant solution for a simple virtual drive needs!
Having such a familiar options for other big (bloated and wasted) virtual drive solutions like automount on system start will make ImgDrive a real competitor to those paid things, with 1000% exceeded features.
Thanks for ImgDrive

**Comment by imgdrive** [comment]
ImgDrive has autorun and automount features.

![image](https://user-images.githubusercontent.com/19568093/167066994-6b7e33f7-217f-4292-ba80-bc6f9fd6cbd6.png)

![image](https://user-images.githubusercontent.com/19568093/167067024-04f7ca30-d9a3-454b-aa06-a65916c3ce94.png)
