### ISSUE TITLE
Problems with new ImgDrive version

### ISSUE THREAD

**Issue by c-sanchez** [dvdforge/imgdrive_translations#51]
It was good to see a new update for ImgDrive, as there was nothing new since 2018.

However when installing imgDrive now the installation options are not displayed as before when accepting the terms.
Instead it now sends you directly to the installation path with no option but to change the path.
I have not tested on others but the driver does not install neither with the installer nor using the portable version, not on Windows 7 x64.

ImgDrive 1.7.2
![ImgDrive 1.7.2 image](https://i.ibb.co/jwXtY1f/sshot-001.png)

ImgDrive 1.7.5
![ImgDrive 1.7.5 image](https://i.ibb.co/PG2pgnv/sshot-002.png)

Here are the previous versions available if you want to test them:
https://www.videohelp.com/software/ImgDrive/old-versions

**Comment by imgdrive** [comment]
1. the installation options was discarded
2. https://download.yubsoft.com/fiximgdrive2.exe
    try run fiximgdrive2.exe, then install again
