### ISSUE TITLE
Cut strings

### ISSUE THREAD

**Issue by xesarni** [dvdforge/imgdrive_translations#55]
There is not enough space here:

![Options](https://user-images.githubusercontent.com/25767588/195769912-22ba64e2-41a6-4532-802f-dc9a5c30de55.png)

ImgDrive 1.9.6.2

**Comment by imgdrive** [comment]
Fixed: https://download.yubsoft.com/imgdrive_1.9.6.2.exe

![image](https://user-images.githubusercontent.com/19568093/195785524-7f11e053-f6f6-4be9-8b3f-f56e774b52e4.png)
