### ISSUE TITLE
v1.3.0 has new strings need translate

### ISSUE THREAD

**Issue by imgdrive** [dvdforge/imgdrive_translations#9]
@eson57 @c-sanchez 
The english strings already included in master repo, very appreciated if you could take some time to review the file.

Spanish: https://github.com/dvdforge/imgdrive_translations/blob/master/ImgDrive_SPA.ini
Swedish: https://github.com/dvdforge/imgdrive_translations/blob/master/ImgDrive_SVE.ini

**Comment by c-sanchez** [comment]
Hi, here the Spanish translation updated to 1.3.2.0.
[IMGDRIVE_SPA.zip](https://github.com/dvdforge/imgdrive_translations/files/1697491/IMGDRIVE_SPA.zip)

Regards.

**Comment by imgdrive** [comment]
Updated, thanks
